# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=2.0.14
maven_group=dev.codedsakura.blossom
mod_slug=BlossomPVP
archives_base_name=blossom-pvp
supported_versions=26.3

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_version=0.160.6
blossomlib_version=2.6.1
